# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29bbec39b6aa10fd3e47c41de0f2a7f9fd9b9adbd68c26713d7ed255106cb963d8468b4d3838e3acfd5d088e5614d7c3fed55b6827871c20d1f66973ed2f5ecf

test:
  secret_key_base: 7ec2d2a6a6dcf1a6f299dfa44a86f989264760dc74e7b381000061b87407833eaf7ac17782e96b70a46b805d65b24921b4b612d9a969cf8a47d1ab47ec734a3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
